// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2QSNW0L4aIGwy7Bb3HLp8MPvNvp1N8Eg',
    appId: '1:185986606023:web:dba5302e8290abb2b6afe2',
    messagingSenderId: '185986606023',
    projectId: 'hirepro-sp',
    authDomain: 'hirepro-sp.firebaseapp.com',
    storageBucket: 'hirepro-sp.appspot.com',
    measurementId: 'G-B2ER4DW4ZW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRDHC8c863lm92H-_f8KVr0LXoS8BkPfo',
    appId: '1:185986606023:android:5de1c1439b498b75b6afe2',
    messagingSenderId: '185986606023',
    projectId: 'hirepro-sp',
    storageBucket: 'hirepro-sp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfTj9QQOu9_kOVJ4wUpUY0AIJZIT6lZME',
    appId: '1:185986606023:ios:8389baaf6a4783ddb6afe2',
    messagingSenderId: '185986606023',
    projectId: 'hirepro-sp',
    storageBucket: 'hirepro-sp.appspot.com',
    iosClientId: '185986606023-qttv6u0qapninhbaok89ag6on1dkrs6k.apps.googleusercontent.com',
    iosBundleId: 'com.example.hirePro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfTj9QQOu9_kOVJ4wUpUY0AIJZIT6lZME',
    appId: '1:185986606023:ios:1c854f0a799ec5e8b6afe2',
    messagingSenderId: '185986606023',
    projectId: 'hirepro-sp',
    storageBucket: 'hirepro-sp.appspot.com',
    iosClientId: '185986606023-vgjkf0c0echlv38qkda564ivhttgld2p.apps.googleusercontent.com',
    iosBundleId: 'com.example.hirePro.RunnerTests',
  );
}
