POST http://localhost:5001/registerSP
Content-Type: application/json

{
  "contact" : "0716960023",
  "name" : "sachini Muthugala",
  "email" : "sachinimuthugala1224@gmail.com", 
  "nic" : "200101101140", 
  "password" : "example123"
}

###
POST http://localhost:5001/loginSP
Content-Type: application/json

{
  "email" : "sachinimuthugala1224@gmail.com", 
  "password" : "example123"
}

###
POST http://localhost:5001/logoutSP

###
GET http://localhost:5001/testGet

###
GET http://localhost:5001/getUser
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMjUiLCJ1c2VyX25hbWUiOiJzYWNoaW5pIE11dGh1Z2FsYSIsInVzZXJfZW1haWwiOiJzYWNoaW5pbXV0aHVnYWxhMTIyNEBnbWFpbC5jb20iLCJpYXQiOjE2OTQyODYwODgsImV4cCI6MTY5NTQ5NTY4OH0.xZ2EpwtOtz80KKEW2Ld54Sw2wzRsC8QXnJJOstt-Rzc

###
POST http://localhost:5001/editUser
Content-Type: application/json

{
  "name" : "John Doe",
  "email" : "newmail@gmail.com",
  "intro" : "New new intro"
}

###
GET http://localhost:5001/getBiddingTasks
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNiIsInVzZXJfbmFtZSI6IlRoYXJ1c2hrYSBNYWR1c2FyYSIsInVzZXJfZW1haWwiOiJtYWR1c2FyYUBnbWFpbC5jb20iLCJpYXQiOjE2OTIwNjUwMDYsImV4cCI6MTY5MzI3NDYwNn0.fg_6UuLqd5HKkdRP0wgi-voDNFUUDW_AohIL8Qjr8vk


###
GET http://localhost:5001/getUser
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNiIsInVzZXJfbmFtZSI6IlRoYXJ1c2hrYSBNYWR1c2FyYSIsInVzZXJfZW1haWwiOiJtYWR1c2FyYUBnbWFpbC5jb20iLCJpYXQiOjE2OTIwNjUwMDYsImV4cCI6MTY5MzI3NDYwNn0.fg_6UuLqd5HKkdRP0wgi-voDNFUUDW_AohIL8Qjr8vk
