POST http://localhost:5001/registerSP
Content-Type: application/json

{
  "contact" : "0771234567",
  "name" : "John Doe",
  "email" : "john3@gmail.com", 
  "nic" : "123456893434", 
  "password" : "example123"
}

###
POST http://localhost:5001/loginSP
Content-Type: application/json

{
  "email" : "john3@gmail.com", 
  "password" : "example123"
}

###
POST http://localhost:5000/logoutSP

###
GET http://localhost:5000/testGet

###
GET http://localhost:5000/getUser

###
POST http://localhost:5000/editUser
Content-Type: application/json

{
  "name" : "John Doe",
  "email" : "newmail@gmail.com",
  "intro" : "New new intro"
}

###
POST http://10.22.167.193:5001/loginSP
Content-Type: application/json

{
  "email" : "john3@gmail.com", 
  "password" : "example123"
}